# -*- coding: utf-8 -*-
"""facemodel.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wWjlegfjhl7ZlGmaNkalv2uut7ZgxRdp
"""

from torchvision import models
import torch
import torch.nn as nn
import os

path='cropped_images'

class_names=os.listdir(path)

model = models.alexnet(pretrained=True)

features=model.classifier[6].in_features

model.classifier[6] = nn.Linear(features,len(class_names))
