# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hIuYslzs5eOfJOSMMXPTL2Lcubq7T4rU
"""

#from dataprocess import *
from dataprocess import *
from facemodel import model as Model


#device=torch.device("cuda:0" if torch.cuda.is_available else "cpu")


Model.load_state_dict(torch.load('model_final'))
#print(Model)

import torch.nn as nn
import torch
criterion=nn.CrossEntropyLoss()

tloss=0
total=0
correct=0
for input,label in test_loader:

  input=input
  label=label
  output=Model(input)
  _,prediction=torch.max(output,1)
  loss=criterion(output,label)
  losses=loss.item() * input.size(0)
  tloss+=losses

  correct+=torch.sum(prediction==label)
  total+=input.size(0)

accuracy=correct/total

test_loss=tloss/dataset_sizes['test']


print('Testing loss:{} Testing Accuracy:{}'.format(test_loss,accuracy*100))



